branches:
  except: release-notes
language: node_js
sudo: false
node_js:
  - 15
cache:
  directories:
    - node_modules
before_install:
  - bash .travis-pre.sh
env:
  global:
    - secure: fGRo+RTDcnWNnYjSgDtHIRFrkXDxYzFrF0JaGs73ZunLXoYbJ5FclaM9+wjw8BbGEEsVbyBYMSHyy8E2Y0VRggal/XlFkKaqQQHSDVuslcM5YdAkcLC8jFSuSzP32X6cY+L9fKszFVaO+vn84lXwiQnqgpOHAtN32/eB//5Ky1s=
    - secure: MmcELlODnZq5EdfKqp8YQBaWHTL76oK8GAbvMaY+MBEj+ddiWRj9xnkU9mKB488Zh/G3sqiqv80QeIPhWzL+cjSXj2v6oCy+PML+aWiWq7KlhSogxjVQrMN0VXew8DKC4/9FwdNf/irNcCm6UaiI0Fw6UcCZ+kVGw4301fciAkw=
    - secure: Vyedcxqn04Or/NZLOeK+pii6YulrSNQrDHCPmoXQh9IVeefOF4NujL/d7+PQuKiRUED3AOw6Ziib6oDzpFamTXXl5SJ4xeKS6V9NpHXunLUlLCuv37siQ+96WvN8r5IHs0BJV/hVKCFbk7IosEdnK1OAx6KyVpYctNdf4qWa4O4=
script: make test-unit-ci
jobs:
  include:
    - stage: Check
      name: Lint
      script: make lint
    - stage: Check
      name: Types
      script: make test-types

    - stage: Unit Test
      name: Coverage
      addons:
        chrome: stable
      env: BROWSER=ChromeHeadlessCI REPORT_COVERAGE=true
      script: make test-unit-cov-ci
    - name: Chrome
      env: BROWSER=Chrome
      addons:
        chrome: stable
      services:
        - xvfb
    - name: Safari
      env: BROWSER=BrowserStackSafari
    - name: iOS 14
      env: BROWSER=BrowserStackIos14
    - name: iOS 13
      env: BROWSER=BrowserStackIos13

    - &e2e
      stage: End-to-End Test
      name: Chrome
      env: BROWSER=BrowserStackChrome
      script: make test-e2e-ci
    - <<: *e2e
      name: Safari
      env: BROWSER=BrowserStackSafari
    - <<: *e2e
      name: iOS 14
      env: BROWSER=BrowserStackIos14
    - <<: *e2e
      name: iOS 13
      env: BROWSER=BrowserStackIos13

    - stage: Publish
      name: Publish Artifacts
      addons:
        apt:
          packages:
            - google-cloud-sdk
      script:
        - openssl aes-256-cbc -K $encrypted_7a8336da16e8_key -iv $encrypted_7a8336da16e8_iv -in gcs.json.enc -out gcs.json -d
        - gcloud auth activate-service-account --key-file=gcs.json
        - make build
        - gsutil cp -Z build/* $GCS_BUCKET_URL/$TRAVIS_COMMIT/
