# TODO: Add published to CDN date to description when the release is marked prerelease: false
name: Create GitHub Release
on:
  repository_dispatch:
    types:
      - release_notes
  push:
    tags:
      - 'v*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Prepare
        id: prep
        run: |
          version=$(echo '${{ github.ref }}' | sed 's/^.*v//')
          changes=$(sed -n "/^### Version $version/,/^###/p" CHANGELOG.md | sed '$d' | sed '1d')
          links=$(cat CHANGELOG.md | grep '^\[')
          echo "::set-output name=name::$version"
          echo "::set-output name=md5-checksum::$(set -- $(md5sum ./build/recurly.min.js); echo $1)"
          echo "::set-output name=sri-hash::$(openssl dgst -sha384 -binary ./build/recurly.min.js | openssl base64 -A)"
          echo "::set-output name=changes::${changes//$'\n'/%0A}"
          echo "::set-output name=links::${links//$'\n'/%0A}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.prep.outputs.name }}
          body: |
            ${{ steps.prep.outputs.changes }}

            ##### Minified MD5 Checksum
            ```
            ${{ steps.prep.outputs.md5-checksum }}
            ```
            ##### [SRI Hash](https://www.srihash.org/)
            ```
            ${{ steps.prep.outputs.sri-hash }}
            ```

            ${{ steps.prep.outputs.links }}
          draft: false
          prerelease: true
